FROM node:20-alpine AS builder
WORKDIR /app
 
COPY libreria-compartida ./libreria-compartida
COPY svc-ingesta/package*.json ./
RUN npm ci --omit=dev
 
FROM node:20-alpine
WORKDIR /app
 
RUN apk update && apk upgrade
 
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/libreria-compartida /libreria-compartida
COPY svc-ingesta/src ./src
 
RUN mkdir -p /app/storage
 
RUN rm -rf /usr/local/lib/node_modules/npm \
           /usr/local/bin/npm \
           /usr/local/bin/npx
 
EXPOSE 8082
CMD ["node", "src/index.js"]